// <auto-generated />
using System;
using GorgeShipping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GorgeShipping.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190625073403_editTypeCode")]
    partial class editTypeCode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GorgeShipping.Models.Address", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressDetail");

                    b.Property<string>("Code");

                    b.Property<string>("District");

                    b.Property<string>("Province");

                    b.Property<string>("TelNo");

                    b.Property<Guid>("UserId");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("GorgeShipping.Models.TelNo", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsVerify");

                    b.Property<string>("TelNumber");

                    b.Property<Guid>("UserId");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("TelephoneNumbers");
                });

            modelBuilder.Entity("GorgeShipping.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GorgeShipping.Models.Address", b =>
                {
                    b.HasOne("GorgeShipping.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GorgeShipping.Models.TelNo", b =>
                {
                    b.HasOne("GorgeShipping.Models.User", "User")
                        .WithMany("TelephoneNumbers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
